### ISSUE TITLE
Erweiterung: Empfehlungen/Guidance

### ISSUE THREAD

**Issue by kopierschnitte** [mameier1234/ioBroker.blueconnect#1]
Super Adapter, läuft auf Anhieb. Vielen Dank!
Bisher habe ich den https://github.com/LordMike/MBW.BlueRiiot2MQTT Code verwendet, jedoch war das wegen Docker und das HASS-Auslegung sehr "bullig".

Einen Vorschlag bzw. Frage hätte ich: Ist es möglich, auch irgendwie an die "Guidance"-Werte zu kommen? Also der Teil, der z. B. sagt "5g Chlor hinzufügen".

**Comment by p3pp0** [comment]
@kopierschnitte was hast du als PoolID benutzt? kriege diesen Fehler: Unauthorized: you cannnot access to this swimming pool
