### ISSUE TITLE
PoolID not found

### ISSUE THREAD

**Issue by p3pp0** [mameier1234/ioBroker.blueconnect#2]
I got the following error:
**Unauthorized: you cannnot access to this swimming pool**

i used "pool name" as poolid. Am i wrong?

@kopierschnitte hast du eine Idee?

**Comment by kopierschnitte** [comment]
Hi!
Ich habe die PoolID aus der BlueConnect App (dort auf Einstellung / Mein BlueConnect). Da stand sie oberhalb der Seriennummer.

**Comment by p3pp0** [comment]
@kopierschnitte 
in der App unter "Mein Blue connect" steht bei mir "Schlüssel" und "Seriennummer"... ich dachte Schlüssel ist dann bestimmt der Blueconnect Key, der in der Adapterconfig verlangt wird...

hab alle kombinationen durch, bei mir kommt immer "Unauthorized: you cannnot access to this swimming pool". Kannst du mir noch mal helfen? Vielleihct bin ich blind.. was genau hast du bei PoolID und Blueconnect Key?

**Comment by p3pp0** [comment]
![Uploading 1F803193-E820-4A8D-AA32-D55B1A9D8F56.jpeg…]()

**Comment by p3pp0** [comment]
![7B8A37B3-E067-45FA-8AEC-571CDACBF8DE](https://user-images.githubusercontent.com/9203649/120083907-58c37d00-c0cc-11eb-8962-c65a3bbcf988.jpeg)

**Comment by kopierschnitte** [comment]
Stimmt, Du hast völlig recht. Ich hatte vorher den "BlueRiiot2MQTT"-Container laufen (https://github.com/LordMike/MBW.BlueRiiot2MQTT). Der hatte mir die PoolID angezeigt und ich hatte sie zum Glück noch gespeichert gehabt. Dabei handelt es sich um eine lange GUID (bei mir 0c7aAAAA-07ba-XXXX-YYYY-ZZZZfb6cdaf8).
Ich weiß leider nicht, wo man sie händisch bekommen kann. Aber vielleicht traust Du Dir zu, obigen Container zu starten und dann die ID auszulesen.
Vielleicht könnte man auch bei der App-Verbindung mitsniffen.

Ich denke auch, die ID kann ganz simpel über die inoffizielle API ausgelesen werden (schafft ja obiger Container auch), aber der Adapter-Entwickler ist glaube ich nicht mehr "anwesend" :-(

**Comment by mameier1234** [comment]
Der "Entwickler" ist noch anwesen, aber leider etwas überfordert.. Er hatte nämlich von einem MItarbeiter hilfe, der nicht mehr greifbar ist.. .

Ich gehe aber mal davon aus, dass die Basis ausbaubar ist.. Es darf gerne mitgeabeitet werden..

**Comment by kopierschnitte** [comment]
Lol. Sorry, das war nicht böse gemeint ;-)
Habe einen ersten Quick & Dirty Workaround gebastelt der bei mir auch schon funktioniert. Konnte bisher leider den Admin-Bereich noch nicht anpassen. Ist meine allererste Arbeit an einem Adapter (und auch bei Github generell) und vieles ist noch neu.
Aber vielleicht kannst Du ja mal drüberschauen?

**Comment by mameier1234** [comment]
Hab ich auch nicht als böse aufgefasst..  Das war auch meine erste Erfahrung mit Github :-)

Pull ist gemergt... kann gerne noch von mehreren getestet werden...
